name: quakemigrate
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter
  - matplotlib <3.3
  - numpy
  - obspy >=1.2
  - pandas ==1.0.*
  - python >=3.7,<3.10
  - pyproj >=2.5
  - scipy
